# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: teacher-profiles.proto for package ''

require 'grpc'
require_relative './teacher-profiles_pb'

module TeacherProfiles
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'TeacherProfiles'

    rpc :Find, TeacherFindRequest, TeacherProfile
    rpc :Where, TeacherWhereRequest, TeacherProfile
  end

  Stub = Service.rpc_stub_class
end
