# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teacher-profiles.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("teacher-profiles.proto", :syntax => :proto3) do
    add_message "TeacherFindRequest" do
      optional :id, :int32, 1
    end
    add_message "TeacherWhereRequest" do
      optional :name, :string, 1
    end
    add_message "TeacherProfile" do
      optional :id, :int32, 1
      optional :name, :string, 2
    end
  end
end

TeacherFindRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("TeacherFindRequest").msgclass
TeacherWhereRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("TeacherWhereRequest").msgclass
TeacherProfile = Google::Protobuf::DescriptorPool.generated_pool.lookup("TeacherProfile").msgclass
