# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: student-profiles.proto for package ''

require 'grpc'
require_relative './student-profiles_pb'

module StudentProfiles
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'StudentProfiles'

    rpc :Find, FindRequest, StudentProfile
    rpc :Where, WhereRequest, StudentProfile
  end

  Stub = Service.rpc_stub_class
end
