# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student-profiles.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("student-profiles.proto", :syntax => :proto3) do
    add_message "FindRequest" do
      optional :id, :int32, 1
    end
    add_message "WhereRequest" do
      optional :name, :string, 1
    end
    add_message "StudentProfile" do
      optional :id, :int32, 1
      optional :name, :string, 2
    end
  end
end

FindRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("FindRequest").msgclass
WhereRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("WhereRequest").msgclass
StudentProfile = Google::Protobuf::DescriptorPool.generated_pool.lookup("StudentProfile").msgclass
